In [1]:
file = open('cats.txt')

In [2]:
file = file.readlines()

In [3]:
file

['In comparison to dogs, cats have not undergone major changes during the domestication process.\n',
 'As cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.\n',
 'A common interactive use of cat for a single file is to output the content of a file to standard output.\n',
 'Cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.\n',
 'In one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.\n',
 'The domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.\n',
 'Domestic cats are similar in size to the other members of the genus Felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).\n',
 'However, if the output is piped or redirected, cat is unnecessary.\n',
 'cat with one named file is safer whe

In [4]:
for i in range(len(file)):
    file[i] = file[i].lower().strip()

In [5]:
file

['in comparison to dogs, cats have not undergone major changes during the domestication process.',
 'as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.',
 'a common interactive use of cat for a single file is to output the content of a file to standard output.',
 'cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.',
 'in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.',
 'the domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.',
 'domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).',
 'however, if the output is piped or redirected, cat is unnecessary.',
 'cat with one named file is safer where human error i

In [6]:
print(file[0])

in comparison to dogs, cats have not undergone major changes during the domestication process.


In [7]:
import re

for i in range(len(file)):
    file[i] = re.split('[^a-z]', file[i])

In [8]:
file

[['in',
  'comparison',
  'to',
  'dogs',
  '',
  'cats',
  'have',
  'not',
  'undergone',
  'major',
  'changes',
  'during',
  'the',
  'domestication',
  'process',
  ''],
 ['as',
  'cat',
  'simply',
  'catenates',
  'streams',
  'of',
  'bytes',
  '',
  'it',
  'can',
  'be',
  'also',
  'used',
  'to',
  'concatenate',
  'binary',
  'files',
  '',
  'where',
  'it',
  'will',
  'just',
  'concatenate',
  'sequence',
  'of',
  'bytes',
  ''],
 ['a',
  'common',
  'interactive',
  'use',
  'of',
  'cat',
  'for',
  'a',
  'single',
  'file',
  'is',
  'to',
  'output',
  'the',
  'content',
  'of',
  'a',
  'file',
  'to',
  'standard',
  'output',
  ''],
 ['cats',
  'can',
  'hear',
  'sounds',
  'too',
  'faint',
  'or',
  'too',
  'high',
  'in',
  'frequency',
  'for',
  'human',
  'ears',
  '',
  'such',
  'as',
  'those',
  'made',
  'by',
  'mice',
  'and',
  'other',
  'small',
  'animals',
  ''],
 ['in',
  'one',
  '',
  'people',
  'deliberately',
  'tamed',
  'cats',
  

In [18]:
for i in range(len(file)):
    for word in file[i]:
        if word == '':
            file[i].remove(word)

In [19]:
file[0]

['in',
 'comparison',
 'to',
 'dogs',
 'cats',
 'have',
 'not',
 'undergone',
 'major',
 'changes',
 'during',
 'the',
 'domestication',
 'process']

In [20]:
file

[['in',
  'comparison',
  'to',
  'dogs',
  'cats',
  'have',
  'not',
  'undergone',
  'major',
  'changes',
  'during',
  'the',
  'domestication',
  'process'],
 ['as',
  'cat',
  'simply',
  'catenates',
  'streams',
  'of',
  'bytes',
  'it',
  'can',
  'be',
  'also',
  'used',
  'to',
  'concatenate',
  'binary',
  'files',
  'where',
  'it',
  'will',
  'just',
  'concatenate',
  'sequence',
  'of',
  'bytes'],
 ['a',
  'common',
  'interactive',
  'use',
  'of',
  'cat',
  'for',
  'a',
  'single',
  'file',
  'is',
  'to',
  'output',
  'the',
  'content',
  'of',
  'a',
  'file',
  'to',
  'standard',
  'output'],
 ['cats',
  'can',
  'hear',
  'sounds',
  'too',
  'faint',
  'or',
  'too',
  'high',
  'in',
  'frequency',
  'for',
  'human',
  'ears',
  'such',
  'as',
  'those',
  'made',
  'by',
  'mice',
  'and',
  'other',
  'small',
  'animals'],
 ['in',
  'one',
  'people',
  'deliberately',
  'tamed',
  'cats',
  'in',
  'a',
  'process',
  'of',
  'artificial',
  's

In [21]:
words = []

for line in file:
    for word in line:
        words.append(word)

In [22]:
words

['in',
 'comparison',
 'to',
 'dogs',
 'cats',
 'have',
 'not',
 'undergone',
 'major',
 'changes',
 'during',
 'the',
 'domestication',
 'process',
 'as',
 'cat',
 'simply',
 'catenates',
 'streams',
 'of',
 'bytes',
 'it',
 'can',
 'be',
 'also',
 'used',
 'to',
 'concatenate',
 'binary',
 'files',
 'where',
 'it',
 'will',
 'just',
 'concatenate',
 'sequence',
 'of',
 'bytes',
 'a',
 'common',
 'interactive',
 'use',
 'of',
 'cat',
 'for',
 'a',
 'single',
 'file',
 'is',
 'to',
 'output',
 'the',
 'content',
 'of',
 'a',
 'file',
 'to',
 'standard',
 'output',
 'cats',
 'can',
 'hear',
 'sounds',
 'too',
 'faint',
 'or',
 'too',
 'high',
 'in',
 'frequency',
 'for',
 'human',
 'ears',
 'such',
 'as',
 'those',
 'made',
 'by',
 'mice',
 'and',
 'other',
 'small',
 'animals',
 'in',
 'one',
 'people',
 'deliberately',
 'tamed',
 'cats',
 'in',
 'a',
 'process',
 'of',
 'artificial',
 'selection',
 'as',
 'they',
 'were',
 'useful',
 'predators',
 'of',
 'vermin',
 'the',
 'domesticat

In [24]:
unique_words = set(words)

In [25]:
len(words)

484

In [26]:
len(unique_words)

254

In [27]:
words_dict = {}

i = 0
for unique_word in unique_words:
    words_dict[unique_word] = i
    i += 1

In [28]:
words_dict

{'october': 0,
 'mid': 1,
 'their': 2,
 'online': 3,
 'patch': 4,
 'you': 5,
 'yosemite': 6,
 'process': 7,
 'small': 8,
 'developed': 9,
 'has': 10,
 'an': 11,
 'os': 12,
 'with': 13,
 'received': 14,
 'more': 15,
 'release': 16,
 'now': 17,
 'symbol': 18,
 'entirely': 19,
 'july': 20,
 'dogs': 21,
 'need': 22,
 'instead': 23,
 'possess': 24,
 'where': 25,
 'separate': 26,
 'ears': 27,
 'and': 28,
 'according': 29,
 'part': 30,
 'command': 31,
 'leopard': 32,
 'typically': 33,
 'most': 34,
 'if': 35,
 'successor': 36,
 'won': 37,
 'incremental': 38,
 'mavericks': 39,
 'installed': 40,
 'app': 41,
 'without': 42,
 'over': 43,
 'sounds': 44,
 'standard': 45,
 'kg': 46,
 'safer': 47,
 'unnecessary': 48,
 'file': 49,
 'closest': 50,
 'used': 51,
 'legibility': 52,
 'osx': 53,
 'just': 54,
 'adjacent': 55,
 'download': 56,
 'comparison': 57,
 'purchase': 58,
 'offered': 59,
 'of': 60,
 'deliberately': 61,
 'or': 62,
 's': 63,
 'felis': 64,
 'often': 65,
 'place': 66,
 'mac': 67,
 'firmware

In [29]:
n = len(file)

In [30]:
n

22

In [31]:
import numpy as np

matrix = np.zeros((22, 254))

In [32]:
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [33]:
matrix.shape

(22, 254)

In [34]:

for i in range(len(file)):
    for u_word, index in words_dict.items():
        for word in file[i]:
            if u_word == word:
                matrix[i, index] += 1        

In [35]:
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [36]:
cos_dist = np.zeros(22)

In [38]:
cos_dist

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [39]:
cos_dist[0] = 1

In [40]:
len(matrix)

22

In [50]:
from scipy.spatial.distance import cosine

for i in range(len(matrix)):
    cos_dist[i] = cosine(matrix[20], matrix[i])

In [51]:
cos_dist

array([0.84275727, 0.96533124, 0.80110194, 0.92307692, 0.87732088,
       0.9561471 , 0.84310709, 0.89121434, 0.85846537, 0.86132495,
       0.79553479, 0.8684413 , 0.84310709, 0.9048697 , 0.81509993,
       0.83642784, 0.76611786, 0.71367186, 0.75464175, 0.75464175,
       0.        , 0.70042766])

In [65]:
cos_dist.max

<function ndarray.max>

In [66]:
cos_dist.max()

0.9653312377359232

In [52]:
best_2 = [[cos_dist[i], i] for i in range(len(cos_dist)) if cos_dist[i] < 0.75]

In [53]:
best_2

[[0.7136718566608999, 17], [0.0, 20], [0.700427655242361, 21]]

In [54]:
best_2[:, 1]

TypeError: list indices must be integers or slices, not tuple

In [55]:
best_2 = np.array(best_2)

In [56]:
print(best_2[:, 1])

[0. 4. 6.]


In [54]:
test = open('cats.txt')

In [55]:
test = test.readlines()

In [56]:
print(test[20])
print(test[17])
print(test[21])

Mac OS X Mountain Lion installs in place, so you won't need to create a separate disk or run the installation off an external drive.

OS X Mountain Lion was released on July 25, 2012 for purchase and download through Apple's Mac App Store, as part of a switch to releasing OS X versions online and every year.

The fifth major update to Mac OS X, Leopard, contains such a mountain of features - more than 300 by Apple's count.
